LJ_POEMS_JSON = 'lj_poems.json'
LJ_MAIN_JSON = 'lj_main.json'

TITLE = 'title'
YEAR = 'year'
MONTH = 'month'
DAY = 'day'
WHERE = 'where'
LANG = 'lang'
IS_TANKA = 'is_tanka'
SOURCE = 'source'
TEXT = 'text'

ENG = 'eng'
RUS = 'rus'
