LJ_POEMS_JSON = 'lj_poems.json'
LJ_MAIN_JSON = 'lj_main.json'

TITLE = 'title'
YEAR = 'year'
MONTH = 'month'
DAY = 'day'
WHERE = 'where'
LANG = 'lang'
IS_TANKA = 'is_tanka'
IS_SONG = 'is_song'
IS_DERIVATIVE = 'is_derivative'
SOURCE = 'source'
TEXT = 'text'
ORIGINAL_BY = 'original_by'
ORIGINAL_LANG = 'original_lang'
ORIGINAL_TITLE = 'original_title'

ENG = 'eng'
RUS = 'rus'
